DOMAIN = "qilowatt"
DATA_CLIENT = "client"
CONF_INVERTER_MODEL = "inverter_model"
CONF_INVERTER_ID = "inverter_id"
CONF_MQTT_USERNAME = "mqtt_username"
CONF_MQTT_PASSWORD = "mqtt_password"
CONF_DEVICE_ID = "device_id"
CONF_BATTERY_SOC_SENSOR = "battery_soc_sensor"